version: '3.8'
services:
  user-service:
    build: ./services/user-service
    ports:
      - "5001:5001"

  product-service:
    build: ./services/product-service
    ports:
      - "5002:5002"

  order-service:
    build: ./services/order-service
    ports:
      - "5003:5003"

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
